

server {
    listen 80;
    # server_name localhost;
    server_name _;

    
    # These two redirect lines are necessary as /site1 implies a file rather than a directory, resutling in /css/style.css file not loading
    location =/site1 {
        return 301 http://$host/site1/;
        }
    location =/site2 {
        return 301 http://$host/site2/;
    }
    
    location /site1/ {
        proxy_pass http://site1/;
    }
    location /site2/ {
        proxy_pass http://site2/;
    }
}
     